## 一般函数

In [2]:
import numpy as np

### 三角函数

*一般三角函数*

* sin(x)
* cos(x)
* tan(x)

*双曲三角函数*

* sinh(x)
* cosh(x)
* tanh(x)

！[常用公式](https://imgsa.baidu.com/baike/s%3D126/sign=da97f79c5bee3d6d26c683c975176d41/b7003af33a87e950be80175712385343fbf2b472.jpg)
！[常用公式](https://imgsa.baidu.com/baike/s%3D127/sign=7fdab152272dd42a5b0905a9343a5b2f/a2cc7cd98d1001e991f1f034ba0e7bec54e79738.jpg)
！[常用公式](https://imgsa.baidu.com/baike/s%3D114/sign=ea9d031871f082022992953e7ffafb8a/060828381f30e924ff4f7b0a4e086e061d95f726.jpg)
！[常用公式](https://imgsa.baidu.com/baike/s%3D131/sign=4fff0e03b751f819f5250749ebb54a76/42166d224f4a20a430ceb4ef97529822730ed0c2.jpg)
！[常用公式](https://imgsa.baidu.com/baike/s%3D127/sign=539908bf48ed2e73f8e9822eb000a16d/b3fb43166d224f4a454794280bf790529822d12b.jpg)
！[常用公式](https://imgsa.baidu.com/baike/s%3D131/sign=906db46305087bf479ec53eac3d2575e/d62a6059252dd42aa5cc8a83043b5bb5c8eab8d5.jpg)

*三角函数反函数*

* arccos(x)
* arctan(x)
* arcsin(x)

* arccosh(x)
* arctanh(x)
* arcsinh(x)
* arctan2(x)

arctan2(x,y) 返回 arctan(x/y)

### 向量操作

*各个函数的意义还有待挖掘，现混个脸熟吧*

* dot(x,y) 
* inner(x,y)
* cross(x,y)
* vdot(x,y)
* outer(x,y)
* kron(x,y)
* tensordot(x,y[,axis])

### 其他操作

* exp(x) 以e为底的指数函数
* log(x) 以e为底的对数函数？
* log10(x) 以10为底的对数计算
* sqrt(x) 开方函数
* absolute(x) 绝对值函数，输入可以是复数
* conjugate(x) 共轭复数
* negative(x) 取反
* ceil(x) 向上取整
* floor(x) 向下取整
* fabs(x) 绝对值，不能用于复数
* hypot(x,y) 给定一个直接三角形的两边，返回其斜边，勾股定理？
* fmod(x，y) 取模运算，即取余数
* maximum(x,y) 取最大值
* minimum(x,.y) 取最小值

hypot 返回对应点（x,y）到原点的距离



In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.hypot(x,y)

array([ 4.12310563,  5.38516481,  6.70820393])

### 类型处理

* iscomplexobj
* iscomplex
* isrealobj
* isreal
* imag
* real
* real_if_close
* isscalar
* isneginf
* isposinf
* isinf
* isfinite
* isnan
* nan_to_num
* common_type
* typename

正无穷：

In [5]:
np.inf

inf

负无穷：

In [6]:
-np.inf

-inf

非法直（Not a number）:

In [7]:
np.nan

nan

检查是否为无穷：

In [8]:
np.isinf(1.0)

False

In [9]:
np.isinf(np.inf)

True

In [10]:
np.isinf(-np.inf)

True

非法直：

In [11]:
np.array([0])/0

/home/jjg/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan])

这并不会报错，而是返回一个非法值。

只有0/0会得到nan，非0直除以0会得到无穷：

In [15]:
a = np.arange(5.0)
b = a / 0.0
b

/home/jjg/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app
/home/jjg/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([ nan,  inf,  inf,  inf,  inf])

nan 与任何数进行比较都是False：

In [16]:
b == np.nan

array([False, False, False, False, False], dtype=bool)

想要找出nan直需要使用isnan:

In [17]:
np.isnan(b)

array([ True, False, False, False, False], dtype=bool)

### 修改形状

* atleast_1d
* atleast_2d
* atleast_3d
* expend_dims
* apply_over_axes
* apply_along_axis
* hstack
* vstack
* dstack
* column_stack
* hsplit
* vsplit
* dsplit
* split
* squeeze


### 其他有用函数

* fix
* mod
* amax
* amin
* ptp
* sum
* cumsum
* prod
* cumprod
* diff
* angle

* unwrap
* sort_complex
* trim_zeros
* fliplr
* flipud
* rot90
* diag
* eye
* select
* extract
* insert

* roots
* poly
* any
* all
* disp
* unique
* nansum
* nanmax
* nanargmax
* nanargmin
* nanmin