## 生成数组的函数

### arange
arange 类似于Python中的 range 函数，只不过返回的不是列表，而是数组：
        arange(start,stop=None, step=1, dtype=None)
产生一个在区间[start, stop)之间，以step为间隔的数组，如果只输入一个参数，则默认从0开始，并以这个直为结束：

In [1]:
import numpy as np
np.arange(4)

array([0, 1, 2, 3])

与range不同，arange允许非整数直输入，产生一个非整数型的数组：

In [2]:
np.arange(0, 2*np.pi, np.pi/4)

array([ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265,
        3.92699082,  4.71238898,  5.49778714])

数组的默认参数由start, stop, step来确定，也可以指定：

In [3]:
np.arange(0, 2*np.pi, np.pi/4, dtype=np.float32)

array([ 0.        ,  0.78539819,  1.57079637,  2.3561945 ,  3.14159274,
        3.92699099,  4.71238899,  5.49778748], dtype=float32)

由于存在精度问题，使用浮点数可能出现问题：

In [4]:
np.arange(1.5, 2.1, 0.3)

array([ 1.5,  1.8,  2.1])

stop的直2.1出现在了数组中，所以使用浮点数的时候要注意

### linspace

        linspace(start, stop, N)
        
产生N个等距分布在[start, stop]间的元素组成的数组，包括start, stop。

In [5]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

### logspace
        logspace(start, stop, N)
产生N个对数等距分布的数组，默认以10为底：

In [7]:
np.logspace(0, 1, 5)

array([  1.        ,   1.77827941,   3.16227766,   5.62341325,  10.        ])

产生的值为[$10^0$, $10^0.25$, $10^0.5$, $10^0.75$, $10^1$]