### 数组的读写

### 从文本中读取数组


In [1]:
import numpy as np

#### 空格（制表符）分割的文本

假如我们有这样的一个空白分割的文件：

In [2]:
%%writefile myfile.txt
2.1 2.3 3.2 1.3 3.1
6.1 3.1 4.2 2.3 1.8

Writing myfile.txt


为了生成数组，我们首先将数据转化成一个列表组成的列表，再将这个列表转换为数组：

In [6]:
data = []

with open("myfile.txt") as f:
    #每次读一行
    for line in f:
        fileds = line.split()
        row_data = [float(x) for x in fileds]
        data.append(row_data)
        
data = np.array(data)

In [7]:
data

array([[ 2.1,  2.3,  3.2,  1.3,  3.1],
       [ 6.1,  3.1,  4.2,  2.3,  1.8]])

不过，更简便的是使用loadtxt方法：

In [10]:
data = np.loadtxt('myfile.txt')
data

array([[ 2.1,  2.3,  3.2,  1.3,  3.1],
       [ 6.1,  3.1,  4.2,  2.3,  1.8]])

### 逗号分隔文件

In [12]:
%%writefile myfile.txt
2.1, 2.3, 3.2, 1.3, 3.1
6.1, 3.1, 4.2, 2.3, 1.8

Overwriting myfile.txt


对于逗号分隔符的文件（通常.csv格式），我们可以稍微修改之前繁琐的过程，将split的参数变成‘，’即可。

不过，loadtxt函数也可以读这样的文件，只需要指定分隔符的参数即可


In [13]:
data = np.loadtxt('myfile.txt', delimiter=',')
data

array([[ 2.1,  2.3,  3.2,  1.3,  3.1],
       [ 6.1,  3.1,  4.2,  2.3,  1.8]])

### loadtxt 函数

        loadtxt(fname, dtype=<type 'float'>,
                commemts='#', delimiter=None,
                converters=None, skiprows=0,
                usecols=None, unpack=False, ndmin=0)
                
loadtxt 有很多可选参数，其中delimiter就是刚才用到的分隔符参数。

skiprows 参数表示忽略开头的行数，可以用来读写含有标题的文本。

In [17]:
%%writefile myfile.txt
X Y Z MAG ANG
2.1 2.3 3.2 1.3 3.1
6.1 3.1 4.2 2.3 1.8

Overwriting myfile.txt


In [18]:
np.loadtxt('myfile.txt', skiprows=1)

array([[ 2.1,  2.3,  3.2,  1.3,  3.1],
       [ 6.1,  3.1,  4.2,  2.3,  1.8]])

此外，有一个功能更为全面的genfromtxt函数，能处理更多的情况，但相应的速度和效率会慢一些。

        genfromtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, 
           skiprows=0, skip_header=0, skip_footer=0, converters=None, 
           missing='', missing_values=None, filling_values=None, usecols=None, 
           names=None, excludelist=None, deletechars=None, replace_space='_', 
           autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, 
           usemask=False, loose=True, invalid_raise=True)