## ufunc 对象

**Numpy**有两种基本对象：ndarray(N-dimensional array object)和 ufunc（universal function object）。ndarray是存储单一数据类型的多维数组,而ufunc则是能够对数组进行处理的函数。    

例如，我们之前所接触的二元操作符对应的**Numpy**函数，如add，就是一种ufunc对象，它可以作用于数组的每一个元素。

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([2,3,4])

np.add(a,b)

array([2, 4, 6])

查看支持的方法：

In [3]:
dir(np.add)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

除此之外，大部分能够作用于数组的数学函数如三角函数等，都是ufunc对象。

特别的，对于二元操作符所对应的ufunc对象，支持以下方法：

### reduce 方法

        op.reduce(a)
        
将op沿着某个轴应用，使得数组a的为数降低一维。

add作用到一维数组上相当于球和：

![求和公式](math03161.svg)


In [4]:
a = np.array([1,2,3,4])

np.add.reduce(a)

10

多维数组默认只按照第一维进行运算：

In [5]:
a = np.array([[1,2,3,],[4,5,6]])

np.add.reduce(a)

array([5, 7, 9])

指定维数：

In [7]:
np.add.reduce(a, 1)

array([ 6, 15])

作用于字符串：

In [8]:
a = np.array(['ab','cd','ef'],np.object)

np.add.reduce(a)

'abcdef'

逻辑运算：

In [9]:
a = np.array([1,1,0,1])

np.logical_and.reduce(a)

False

In [10]:
np.logical_or.reduce(a)

True

### accumulate 方法

        op.accumulate(a)
        
accumulate可以看成保存reduce每一步的结果所形成的数组。

![计算公式2](math03162.svg)

与之前类似：

In [11]:
a = np.array([1,2,3,4])

np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [13]:
a = np.array(['ab','cd','ef'],np.object)

np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [15]:
a = np.array([1,1,0,1])

np.logical_and.accumulate(a)

array([ True,  True, False, False], dtype=bool)

In [16]:
np.logical_or.accumulate(a)

array([ True,  True,  True,  True], dtype=bool)

### reduceat 方法

        op.reduceat(a, indices)
        
reduceat 方法将操作符运用到指定的下标上，返回一个与indices大小相同的数组：

![计算公式3](math03163.svg)


In [18]:
a = np.array([1, 10, 20, 30, 40, 50])
indices = np.array([1,4])

np.add.reduceat(a, indices)

array([60, 90])

这里，indices为[1, 4]，所以60表示从下标1（包括）加到下标4（不包括）的结果，90表示从下标4（包括）家到结尾的结果。

### outer 方法

        op.outer(a,b)
        
对于a中每一个元素，将op运用到它和b的每一个元素上所得到的结果：

In [19]:
a = np.array([0,1])
b = np.array([1,2,3])

np.add.outer(a, b)

array([[1, 2, 3],
       [2, 3, 4]])

注意有顺序的区别：

In [20]:
np.add.outer(b,a)

array([[1, 2],
       [2, 3],
       [3, 4]])