## choose 函数实现条件筛选

对于数组，我们有时候需要进行类似switch和case进行条件选择，此时使用choose函数十分方便：

In [2]:
import numpy as np

In [3]:
control = np.array([[1,0,1],
                   [2,1,0],
                   [1,2,2]])

np.choose(control, [10,11,12])

array([[11, 10, 11],
       [12, 11, 10],
       [11, 12, 12]])

choose(index,choices),使用前面一个数组作为索引取索引后面一个数组内的值。

上面的例子中，choose将0，1，2对应的值映射为了10，11，12，这里的0，1，2表示对应的下标。

事实上，choose不仅仅能够接受下标参数，还可以接受小表所在的位置：

In [6]:
i0 = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])
i2 = np.array([[20,21,22],
              [23,24,25],
              [26,27,28]])
control = np.array([[1,0,1],
                  [2,1,0],
                  [1,2,2]])

np.choose(control,[i0,10,i2])

array([[10,  1, 10],
       [23, 10,  5],
       [10, 27, 28]])

这里，control传入第一个1，对应的是10，传入的第一个0对应于i0相应位置的值即1：第一个0，表示选中[i0,10,12]中的第一个元素i0，第一个0的索引位置是（0，1），相应的在i0中缩影位置（0，1）所对应的值为1.剩下的以此类推。

下面的例子将数组中所有小于10的值变成了10.

In [7]:
a = np.array([[0,1,2],
             [10,11,12],
             [20,21,22]])

a < 10

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [8]:
np.choose(a < 10, (a, 10))

array([[10, 10, 10],
       [10, 11, 12],
       [20, 21, 22]])

下面的例子将数组中所有小于10的值变成了10，大于15的值变成了15.

In [11]:
a = np.array([[0, 1, 2],
              [10, 11, 12],
              [20, 21, 22]])

lt = a < 10
gt = a > 15

choice = lt + 2*gt
choice

array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])

In [12]:
np.choose(choice, (a, 10, 15))

array([[10, 10, 10],
       [10, 11, 12],
       [15, 15, 15]])