## 记录数组

记录数组（record array）与结构数组类似：

In [1]:
import numpy as np

质点类型：

In [3]:
partical_dtype = np.dtype([('mass','float'),
                           ('velocity','float')])

生成记录数组，要用numpy.rec里的fromrecords方法：

In [5]:
from numpy import rec

particals_rec = rec.fromrecords([(1,1),(1,2),(2,1),(1,3)],
                                dtype = partical_dtype)

In [6]:
particals_rec

rec.array([(1.0, 1.0), (1.0, 2.0), (2.0, 1.0), (1.0, 3.0)], 
          dtype=[('mass', '<f8'), ('celocity', '<f8')])

记录数组中，域可以通过属性来获得：

In [7]:
particals_rec.mass

array([ 1.,  1.,  2.,  1.])

不过，记录数组的运行效率要比结构化数组慢一些。

也可以通过将一个结构数组看成记录数组。

In [8]:
particals = np.array([(1,1),(1,2),(2,1),(1,3)],
                     dtype = partical_dtype)

使用view 方法看成recarray:

In [9]:
particals_rec = particals.view(np.recarray)

In [10]:
particals_rec.mass

array([ 1.,  1.,  2.,  1.])

In [15]:
particals_rec.celocity

array([ 1.,  2.,  1.,  3.])

对于自定义类型，可以通过它的names属性来查看它有那些域：

In [16]:
particals.dtype.names

('mass', 'celocity')